export const StorageConst = {
  APP_LOGO_DIR:{
    src:"/images/logos/app_logo.svg",
    alt:"Logo"
  },
  GOOGLE_DIR:{
    src:"/images/logos/google.svg",
    alt:"Google"
  },
  DISCORD_DIR:{
    src:"/images/logos/discord.svg",
    alt:"Discord"
  },
  TWITTER_DIR:{
    src:"/images/logos/skype.svg",
    alt:"Twitter"
  },
  METAMASK_DIR:{
    src:"/images/logos/metamask.svg",
    alt:"Metamask"
  }
}
