apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NEXTAUTH_URL: http://localhost:3000
  NEXT_PUBLIC_API_URL: api.backend.svc.cluster.local
  GOOGLE_ID: 231176583634-fa44vn4cmt5ugnja56pg2ct89kr7m4vq.apps.googleusercontent.com
  TWITTER_ID: OEZrTkRPRVkxc3NwWmVnMmRJVlI6MTpjaQ
  DISCORD_ID: 1095011377493577769
