apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: questx
  NEXT_PUBLIC_API_URL: api.backend.svc.cluster.local
  GOOGLE_ID: 231176583634-fa44vn4cmt5ugnja56pg2ct89kr7m4vq.apps.googleusercontent.com
  GOOGLE_SECRET: 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
  TWITTER_ID: OEZrTkRPRVkxc3NwWmVnMmRJVlI6MTpjaQ
  TWITTER_SECRET: z25SmzWbAKSiGAj2u4KY8KKLHaDB9B9XcHZW3B7WNMaDNK8JgIngXxJJILKWIMD-0kD1N5aUXtrjvSWAKMCgBwspoFKpDu_34nbN

  DISCORD_ID: 1095011377493577769
  DISCORD_SECRET: f4A3EKtwBEwWiaGb86pofQ3kMtH9YL9l
