name: test workflow

on:
  pull_request:
    branches: ['staging', 'production', 'develop']
    # types: ['closed']

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }} # TODO: update Google Cloud project id
  GAR_LOCATION: ${{ vars.GAR_LOCATION }} # TODO: update Artifact Registry location
  SERVICE: ${{ vars.SERVICE_NAME }} # TODO: update Cloud Run service name
  APP_NAME: ${{ vars.APP_NAME }}
  GKE_CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
  CLUSTER_REGION: ${{ vars.CLUSTER_REGION }}
  ENV_FILE: ${{ vars.ENV_FILE }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  DOMAIN: ${{ vars.DOMAIN }}

jobs:
  deploy:
    # if: ${{ github.event.pull_request.merged }}
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: ${{ github.base_ref }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: Logging
        run: |-
          gcloud compute forwarding-rules list --filter=\"name=( 'frontend-staging-https' )\"
