name: test workflow

on:
  pull_request:
    branches: ['staging', 'production', 'develop']
    # types: ['closed']

env:
  GCP_STAGING_CREDENTIALS: ${{ secrets.GCP_STAGING_CREDENTIALS }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  DOMAIN: ${{ vars.DOMAIN }}

jobs:
  deploy:
    # if: ${{ github.event.pull_request.merged }}
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: ${{ github.base_ref }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
          credentials_staging_json: '${{ env.GCP_STAGING_CREDENTIALS }}'

      - name: Logging
        run: |-
          ips=$(gcloud compute forwarding-rules list)

          echo $ips
